### ISSUE TITLE
TKService.dll is broken

### ISSUE THREAD

**Issue by donovaly** [apeltauer/FreeCAD#15]
The latest LibPack 12.5.3 contains a broken TKService.dll.

It took me a while to figure out that it has a missing and even unneeded dependency to a LIBFREETYPE-6__.DLL. See this thread for details:
https://forum.freecadweb.org/viewtopic.php?p=550142#p550253

**Comment by apeltauer** [comment]
Created opencascade 7.6 without these dependencies

**Comment by donovaly** [comment]
> Created opencascade 7.6 without these dependencies

Many thanks!

However for FC 0.19 we cannot distribute OCC 7.6, we must use OCC 7.5.x. So it would help us if you could provide a LibPack with OCC 7.5.3 + plus the fixes from @chennes . With this I could provide a Windows installer for FC 0.19.3 and this way we could finish the release process of FC 0.19.3.

So we will need 2 LibPacks parallel, one with OCC 7.5 for FC 0.19 and one with OCC 7.6 for FC 0.20.

**Comment by apeltauer** [comment]
The first libpack i will create is with occ7.6...

**Comment by donovaly** [comment]
Fixed in LP 12.5.4.
