### ISSUE TITLE
Update GMSH to at least 4.8.3

### ISSUE THREAD

**Issue by donovaly** [apeltauer/FreeCAD#16]
During the release process of FC 0.19.2 we found out that to be able to use the FEM WB properly we need at least GMSH 4.8.3. So the LibPack must be updated to this (currently already a version 4.8.4 is available).

**Comment by donovaly** [comment]
To fix this issue, you can take just the GMSH .exe file from the zip I linked in #19.

**Comment by apeltauer** [comment]
The exe is missing in the provided zip file....

**Comment by donovaly** [comment]
I just checked and it is correctly in https://github.com/donovaly/FreeCADInstProj/releases/download/LibPack-fixes-1/Changes-for-LibPack-12-5-3.zip in the bin folder

**Comment by apeltauer** [comment]
sorry i looked in the wrong file :)

**Comment by donovaly** [comment]
Fixed in LP 12.5.4.
