### ISSUE TITLE
Update Qt to 5.15.2

### ISSUE THREAD

**Issue by donovaly** [apeltauer/FreeCAD#17]
During the release process of FC 0.19.2 we found out that FC is affected by regression bugs in Qt 5.15. These are fixed in Qt 5.15.2. Therefore the LibPack must contain Qt 5.15.2.

**Comment by apeltauer** [comment]
Used QT 5.15.2

**Comment by donovaly** [comment]
> Used QT 5.15.2

So you will do or you already did? In the case of the latter, at least in the current LibPack 12.5.3 contains the DLLs from 5.15.1.

**Comment by apeltauer** [comment]
i am creating the libpack right now.... :)

**Comment by donovaly** [comment]
Fixed in LP 12.5.4.
